---
default_stages: [commit-msg, pre-commit, pre-push]

repos:
  - repo: builtin
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # v1.38.0
    hooks:
      - id: yamllint
        name: Check YAML files with yamllint
        entry: yamllint -c .yamllint.yaml --strict
        types: [yaml]

  - repo: https://github.com/errata-ai/vale
    rev: f544f4923eb1c7d322c18e35f96333ef8ac29efa # v3.13.1
    hooks:
      - id: vale
        args: [--minAlertLevel=error]
        exclude: ^test.*\.md$
      - id: vale
        name: vale (commit message)
        stages: [commit-msg]
        args: [--ext=.md, --minAlertLevel=error]

  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: 9f07a8f89dc360f6db3cc0ad9c1953148e9f706f # v0.1.44
    hooks:
      - id: rumdl-fmt
      - id: rumdl

  - repo: local
    hooks:
      - id: cog-verify
        name: conventional commits
        entry: cog verify --file
        language: system
        stages: [commit-msg]
        always_run: true
      - id: cspell
        name: cspell
        entry: cspell --no-summary --no-progress --no-must-find-files
        language: system
        types: [text]
      - id: cspell-commit
        name: cspell-commit
        entry: cspell --no-summary --no-progress --language-id commit-msg
        language: system
        stages: [commit-msg]
        types: [text]
