---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Python and Node tooling
        run: |
          pip install yamllint
          npm install -g cspell

      - name: Lint YAML
        run: yamllint --strict .

      - name: Check spelling
        run: cspell .

      - name: Lint Markdown
        uses: rvben/rumdl@e2084bd1bc70402a142a6c65475a0b07ae687847 # v0.1.95
        with:
          path: .
          report-type: annotations

      - name: Lint GitHub Actions workflows
        uses: raven-actions/actionlint@e01d1ea33dd6a5ed517d95b4c0c357560ac6f518 # v2

      - name: Lint prose
        uses: vale-cli/vale-action@85f9f7f2c5f449ac0ae5b66662961bae3f77ca6a # 2.1.2
        with:
          files: .
          vale_flags: "--glob=!test-*.md --minAlertLevel=error"
          fail_on_error: "true"
          filter_mode: nofilter
